# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard_master_constraints.xdc

# IP: ip/blk_mem_bluenocross/blk_mem_bluenocross.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_bluenocross || ORIG_REF_NAME==blk_mem_bluenocross} -quiet] -quiet
