# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.cache/wt [current_project]
set_property parent.project_path C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/redcrossing.coe
add_files C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/bluenocrossing.coe
add_files C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/cidarlogo.coe
add_files C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/background.coe
add_files C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/bluecrossing.coe
read_verilog -library xil_defaultlib {
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/Memory.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/VGAcontrol.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/disp_char.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/display.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/img_processing_code/euclid_px_diff.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/img_processing_code/fg_classify.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/img_processing_code/imgproc_schedule.v
  C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/new/main.v
}
read_ip -quiet C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_bluenocross/blk_mem_bluenocross.xci
set_property used_in_implementation false [get_files -all c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_bluenocross/blk_mem_bluenocross_ooc.xdc]

read_ip -quiet C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_logo/blk_mem_logo.xci
set_property used_in_implementation false [get_files -all c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_logo/blk_mem_logo_ooc.xdc]

read_ip -quiet C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_redcross/blk_mem_redcross.xci
set_property used_in_implementation false [get_files -all c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_redcross/blk_mem_redcross_ooc.xdc]

read_ip -quiet C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_bluecross/blk_mem_bluecross.xci
set_property used_in_implementation false [get_files -all c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_bluecross/blk_mem_bluecross_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard_master_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard_master_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
