# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_logo/blk_mem_logo.xci
# IP: The module: 'blk_mem_logo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_logo/blk_mem_logo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_logo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_logo/blk_mem_logo.xci
# IP: The module: 'blk_mem_logo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jal02005/Documents/fixed_micro/Micronaut/jw_display_code/zedboard.srcs/sources_1/ip/blk_mem_logo/blk_mem_logo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_logo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
